# Configuração do pré-commit para manter qualidade do código
repos:
  # Hooks básicos
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace        # Remove espaços em branco no final das linhas
      - id: end-of-file-fixer         # Garante quebra de linha no final dos arquivos
      - id: check-yaml                # Valida arquivos YAML
      - id: check-json                # Valida arquivos JSON
      - id: check-toml                # Valida arquivos TOML
      - id: check-added-large-files   # Previne commit de arquivos grandes
      - id: check-merge-conflict      # Detecta marcadores de merge conflict
      - id: debug-statements          # Detecta declarações de debug

  # Formatação com Black
  - repo: https://github.com/psf/black
    rev: 24.12.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  # Linting com flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]

  # Imports organizados
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile, black]

  # Verificação de tipos com mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--ignore-missing-imports]

  # Verificação de segurança
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
        args: [-r, ., -f, json, -o, bandit-report.json]
        exclude: ^tests/
