version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:16-alpine  # Usando uma imagem leve do Postgres
    container_name: veterinaria_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # Carrega as variáveis de ambiente do arquivo .env
    env_file:
      - ./.env
    ports:
      - "5432:5432" # Mapeia a porta do contêiner para a do host

  # Serviço da Aplicação FastAPI
  app:
    container_name: veterinaria_api
    build: .  # Constrói a imagem a partir do Dockerfile na pasta atual
    command: ./entrypoint.sh # Comando para iniciar o serviço
    volumes:
      - .:/app # Mapeia o código local para o contêiner para live-reloading
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db # Garante que o serviço 'db' inicie antes do 'app'

volumes:
  postgres_data: